stages:
  obter_dados:
    cmd: python -m src.data.get_data fiap-ds-mlops dataset/laptopPrice.csv data/raw/laptopPrice.csv
    deps:
    - src/data/get_data.py
    outs:
    - data/raw/laptopPrice.csv

  processar_dataset:
    cmd: python -m src.data.make_dataset data/raw/laptopPrice.csv data/processed/laptop-pricing.csv
    deps:
    - src/data/make_dataset.py
    - data/raw/laptopPrice.csv
    outs:
    - data/processed/laptop-pricing.csv

  processar_features:
    cmd: python -m src.data.make_features data/processed/laptop-pricing.csv data/processed/laptop-pricing-features.csv
    deps:
    - src/data/make_features.py
    - data/processed/laptop-pricing.csv
    outs:
    - data/processed/laptop-pricing-features.csv

  treinamento:
    cmd: python -m src.models.train_model data/processed/laptop-pricing-features.csv
      models/model.pkl
    deps:
    - src/models/train_model.py
    - data/processed/laptop-pricing-features.csv
    outs:
    - models/model.pkl

artifacts:
  laptop-pricing:
    path: models/model.pkl
    type: model
    desc: Model to predict laptop pricing.
    labels:
    - regression

metrics:
- dvclive/metrics.json

plots:
- dvclive/plots/metrics:
    x: step

- reports/figures/true_vs_predicted.png
